/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerifikasiRouteImport } from './routes/_app.verifikasi'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppStatusApprovalRouteImport } from './routes/_app.status-approval'
import { Route as AppPinjamanRouteImport } from './routes/_app.pinjaman'
import { Route as AppPesanRouteImport } from './routes/_app.pesan'
import { Route as AppPengembalianRouteImport } from './routes/_app.pengembalian'
import { Route as AppPengambilanRouteImport } from './routes/_app.pengambilan'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppKatalogRouteImport } from './routes/_app.katalog'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAsetRouteImport } from './routes/_app.aset'
import { Route as AppApprovalRouteImport } from './routes/_app.approval'
import { Route as AppPinjamanBaruRouteImport } from './routes/_app.pinjaman.baru'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifikasiRoute = AppVerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusApprovalRoute = AppStatusApprovalRouteImport.update({
  id: '/status-approval',
  path: '/status-approval',
  getParentRoute: () => AppRoute,
} as any)
const AppPinjamanRoute = AppPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AppRoute,
} as any)
const AppPesanRoute = AppPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AppRoute,
} as any)
const AppPengembalianRoute = AppPengembalianRouteImport.update({
  id: '/pengembalian',
  path: '/pengembalian',
  getParentRoute: () => AppRoute,
} as any)
const AppPengambilanRoute = AppPengambilanRouteImport.update({
  id: '/pengambilan',
  path: '/pengambilan',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppKatalogRoute = AppKatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAsetRoute = AppAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalRoute = AppApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AppRoute,
} as any)
const AppPinjamanBaruRoute = AppPinjamanBaruRouteImport.update({
  id: '/baru',
  path: '/baru',
  getParentRoute: () => AppPinjamanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approval': typeof AppApprovalRoute
  '/aset': typeof AppAsetRoute
  '/dashboard': typeof AppDashboardRoute
  '/katalog': typeof AppKatalogRoute
  '/laporan': typeof AppLaporanRoute
  '/pengambilan': typeof AppPengambilanRoute
  '/pengembalian': typeof AppPengembalianRoute
  '/pesan': typeof AppPesanRoute
  '/pinjaman': typeof AppPinjamanRouteWithChildren
  '/status-approval': typeof AppStatusApprovalRoute
  '/users': typeof AppUsersRoute
  '/verifikasi': typeof AppVerifikasiRoute
  '/pinjaman/baru': typeof AppPinjamanBaruRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approval': typeof AppApprovalRoute
  '/aset': typeof AppAsetRoute
  '/dashboard': typeof AppDashboardRoute
  '/katalog': typeof AppKatalogRoute
  '/laporan': typeof AppLaporanRoute
  '/pengambilan': typeof AppPengambilanRoute
  '/pengembalian': typeof AppPengembalianRoute
  '/pesan': typeof AppPesanRoute
  '/pinjaman': typeof AppPinjamanRouteWithChildren
  '/status-approval': typeof AppStatusApprovalRoute
  '/users': typeof AppUsersRoute
  '/verifikasi': typeof AppVerifikasiRoute
  '/pinjaman/baru': typeof AppPinjamanBaruRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/approval': typeof AppApprovalRoute
  '/_app/aset': typeof AppAsetRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/katalog': typeof AppKatalogRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/pengambilan': typeof AppPengambilanRoute
  '/_app/pengembalian': typeof AppPengembalianRoute
  '/_app/pesan': typeof AppPesanRoute
  '/_app/pinjaman': typeof AppPinjamanRouteWithChildren
  '/_app/status-approval': typeof AppStatusApprovalRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/verifikasi': typeof AppVerifikasiRoute
  '/_app/pinjaman/baru': typeof AppPinjamanBaruRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approval'
    | '/aset'
    | '/dashboard'
    | '/katalog'
    | '/laporan'
    | '/pengambilan'
    | '/pengembalian'
    | '/pesan'
    | '/pinjaman'
    | '/status-approval'
    | '/users'
    | '/verifikasi'
    | '/pinjaman/baru'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approval'
    | '/aset'
    | '/dashboard'
    | '/katalog'
    | '/laporan'
    | '/pengambilan'
    | '/pengembalian'
    | '/pesan'
    | '/pinjaman'
    | '/status-approval'
    | '/users'
    | '/verifikasi'
    | '/pinjaman/baru'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/approval'
    | '/_app/aset'
    | '/_app/dashboard'
    | '/_app/katalog'
    | '/_app/laporan'
    | '/_app/pengambilan'
    | '/_app/pengembalian'
    | '/_app/pesan'
    | '/_app/pinjaman'
    | '/_app/status-approval'
    | '/_app/users'
    | '/_app/verifikasi'
    | '/_app/pinjaman/baru'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verifikasi': {
      id: '/_app/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof AppVerifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status-approval': {
      id: '/_app/status-approval'
      path: '/status-approval'
      fullPath: '/status-approval'
      preLoaderRoute: typeof AppStatusApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pinjaman': {
      id: '/_app/pinjaman'
      path: '/pinjaman'
      fullPath: '/pinjaman'
      preLoaderRoute: typeof AppPinjamanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesan': {
      id: '/_app/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof AppPesanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengembalian': {
      id: '/_app/pengembalian'
      path: '/pengembalian'
      fullPath: '/pengembalian'
      preLoaderRoute: typeof AppPengembalianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengambilan': {
      id: '/_app/pengambilan'
      path: '/pengambilan'
      fullPath: '/pengambilan'
      preLoaderRoute: typeof AppPengambilanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/katalog': {
      id: '/_app/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof AppKatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aset': {
      id: '/_app/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof AppAsetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approval': {
      id: '/_app/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof AppApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pinjaman/baru': {
      id: '/_app/pinjaman/baru'
      path: '/baru'
      fullPath: '/pinjaman/baru'
      preLoaderRoute: typeof AppPinjamanBaruRouteImport
      parentRoute: typeof AppPinjamanRoute
    }
  }
}

interface AppPinjamanRouteChildren {
  AppPinjamanBaruRoute: typeof AppPinjamanBaruRoute
}

const AppPinjamanRouteChildren: AppPinjamanRouteChildren = {
  AppPinjamanBaruRoute: AppPinjamanBaruRoute,
}

const AppPinjamanRouteWithChildren = AppPinjamanRoute._addFileChildren(
  AppPinjamanRouteChildren,
)

interface AppRouteChildren {
  AppApprovalRoute: typeof AppApprovalRoute
  AppAsetRoute: typeof AppAsetRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKatalogRoute: typeof AppKatalogRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPengambilanRoute: typeof AppPengambilanRoute
  AppPengembalianRoute: typeof AppPengembalianRoute
  AppPesanRoute: typeof AppPesanRoute
  AppPinjamanRoute: typeof AppPinjamanRouteWithChildren
  AppStatusApprovalRoute: typeof AppStatusApprovalRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVerifikasiRoute: typeof AppVerifikasiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalRoute: AppApprovalRoute,
  AppAsetRoute: AppAsetRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKatalogRoute: AppKatalogRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPengambilanRoute: AppPengambilanRoute,
  AppPengembalianRoute: AppPengembalianRoute,
  AppPesanRoute: AppPesanRoute,
  AppPinjamanRoute: AppPinjamanRouteWithChildren,
  AppStatusApprovalRoute: AppStatusApprovalRoute,
  AppUsersRoute: AppUsersRoute,
  AppVerifikasiRoute: AppVerifikasiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
